### PR TITLE
Adding function to get timezone abbreviation from name

### PR DESCRIPTION
**Pull request by kkavchakHT**

### CODE REVIEW

**Comment by tkuchiki** [comment]
Thank you for your Pull Request.
Just a moment, please.

**Comment by tkuchiki** [comment]
@kkavchakHT I'm sorry for the late reply.
I understand your pull request.

I simplified, and supported the daylight saving time.

```go
func GetTimezoneAbbreviation(timezoneName string, dst ...bool) (string, error) {
        loc, err := time.LoadLocation(timezoneName)
        if err != nil {
                return "", err
        }

        var zone string

        if len(dst) == 0 || !dst[0] {
                now := time.Now()
                zone, _ = time.Date(now.Year(), time.January, 1, 0, 0, 0, 0, time.UTC).In(loc).Zone()
        } else {
                // considering DST
                zone, _ = time.Now().In(loc).Zone()
        }

        return zone, nil
}
```

What do you think?

**Comment by kkavchakHT** [comment]
@tkuchiki The simplified version looks good.

**Comment by tkuchiki** [comment]
@kkavchakHT I'm sorry for the late reply.
Released [v0.1.2](https://github.com/tkuchiki/go-timezone/releases/tag/v0.1.2).

**Pull request merged**
